worker_processes 1;

events { worker_connections 1024; }

http {
    sendfile on;

    upstream ms-core {
        server ms-core-agricola:8000;
    }

    upstream ms-inspecciones {
        server ms-inspecciones:8000;
    }

    map $http_origin $cors_origin {
        default "";
        "http://localhost:4200" "http://localhost:4200";
        "https://ica-5.vercel.app" "https://ica-5.vercel.app";
    }

    server {
        listen 80;

        # Configuración CORS global
        add_header 'Access-Control-Allow-Origin' $cors_origin always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;

        # Opciones preflight
        if ($request_method = 'OPTIONS') {
            return 204;
        }

        # Rutas para el MS Core Agrícola
        location /api/core/ {
            proxy_pass         http://ms-core/;
            proxy_redirect     off;
            proxy_hide_header  'Access-Control-Allow-Origin';
            proxy_hide_header  'Access-Control-Allow-Credentials';
            proxy_hide_header  'Access-Control-Allow-Methods';
            proxy_hide_header  'Access-Control-Allow-Headers';
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

        # Rutas para el MS Inspecciones
        location /api/inspeccion/ {
            proxy_pass         http://ms-inspecciones/;
            proxy_redirect     off;
            proxy_hide_header  'Access-Control-Allow-Origin';
            proxy_hide_header  'Access-Control-Allow-Credentials';
            proxy_hide_header  'Access-Control-Allow-Methods';
            proxy_hide_header  'Access-Control-Allow-Headers';
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }
    }
}
